### ISSUE TITLE
broken on modern stack :(

### ISSUE THREAD

**Issue by silky** [silky/literate-readme#4]
i don't know why:

```
05:07 PM noon ∈ literate-readme (master*) ♫ ./README.lhs

/home/noon/dev/literate-readme/README.md:2:1: error:
    parse error on input ‘>’
```

**Comment by mhitza** [comment]
You can replace the first two lines of the file with

```shell
#!/usr/bin/env -S stack runghc --resolver lts-8.12 --package turtle --package markdown-unlit -- "-pgmL markdown-unlit"
```

This uses the [env -S flag](https://en.wikipedia.org/wiki/Shebang_(Unix)#Character_interpretation) which seems to be less portable in general but should work work across any modern distribution (and OSX).

I was not able to preserve the `stack script` invocation, as the additional parameters passed ("-pgmL ...") would fail, but seems to work with `stack runghc`.

**Comment by silky** [comment]
thanks for looking in to this @mhitza - unfortunately, this doesn't work for me on ubuntu :(

**Comment by silky** [comment]
annoyingly, i "fixed" it, because it turns out you don't even need the `markdown-unlit` stuff 

_however_

the code sections have to start with ">" instead of actual code sections in markdown, AND you can't use the "#" style for the headings

the main thing is that by forcing code sections to be in the markdown-equiv of quotes, it totally breaks the presentation :(

**Comment by silky** [comment]
re-opened as this still isn't fixed; but at least this version _runs_, at the cost of being completely unreadable as a readme with code.

**Comment by silky** [comment]
ugh, i fully forgot why i even needed markdown-unlit, which is precisely for this reason!

i'll try and have a proper look at this later.

**Comment by silky** [comment]
okay; i just hacked it by putting in an intermediate script so all the stack options go in there

lame (because it hides implementation details), but it works.
